SELECT  CUSTOMER_TERM_ID
, cts.CUSTOMER_ID	
, TERM_ID	
, TERM_START_DATE	
, COHORT	
, COHORT_WEEK_WITHOUT_HOLIDAYS	
, IS_HOLIDAY_TERM	
, MEAL_ORDER_ID	
, ORDER_STATU	
, SUBSCRIPTION_STATUS	
, RUNNING_TOTAL_FULFILLED_ORDER_COUNT	
, LAST_EIGHT_WEEK_ORDER_COUNT	
, CONTAINS_AUTOSELECTION	
, CONSECUTIVE_SKIP_COUNT

, FIRST_MEAL_ORDER_ID	
, FIRST_ORDER_SIZE	
, LATEST_COHORT_WEEK_WITHOUT_HOLIDAYS	
, IS_ACTIVE_OVEN_USER	
, LATEST_STATUS	
, IS_FIRST_OVEN_AFFIRM_ORDER	
, AGE	
, GENDER	
, ETHNICITY	
, EDUCATION_LEVEL	
, MARITAL_STATUS	
, EST_HOUSEHOLD_INCOME
, EST_HOUSEHOLD_INCOME_RANGE	
, HOME_OWNERSHIP	
, HOUSEHOLD_SIZE	
, HOUSEHOLD_ADULT_COUNT	
, LIKELIHOOD_OF_CHILDREN	
, DINING_OUT_SPEND	
, ALCOHOL_SPEND	
, TECH_ADOPTION	
, ENVIRONMENTAL_CONSCIOUSNESS	
, COUNTY_TYPE	
, COUNTY_POPULATION	
, FITNESS_ENTHUSIAST_PROB	
, BUYS_KITCHEN_AID_APPLIANCES	
, ORGANIC_PURCHASER	
, BRAND_LOYALIST	
, TRENDSETTER	
, DEAL_SEEKER	
, RECREATIONAL_SHOPPER	
, QUALITY_CONSCIOUS	
, IMPULSE_BUYER	
, MAINSTREAM_ADOPTER	
, NOVELTY_SEEKER	
, GROCERY_DELIVERY_USER	
, FOODIE	
, DO_NOT_MAIL	
, WAREHOUSE_CLUB_MEMBERSHIP_PROB	
, LOYALTY_CARD_PROB	
, MAGAZINE_PURCHASE_PROB	
, FAST_FOOD_PROB	
, HEALTHY_LIVING_PROB

, OVEN_ORDER_ID 
, ORDER_TIME	
, STATUS	
, OVEN_PURCHASE_PRICE	
, OVEN_ORDER_SKU_FORMATTED

, CASE WHEN order_statu = 'skipped' THEN 1 ELSE 0 END AS skipped

FROM customer_term_summary AS cts
LEFT JOIN customer_facts AS cf
ON cts.customer_id = cf.customer_id
LEFT JOIN oven_orders AS oo
ON cf.customer_id = oo.customer_id
